import type { Appearance } from "@clerk/types";

export const clerkAppearance: Appearance = {
  variables: {
    colorPrimary: "#3A90C3",
    colorText: "#0F172A",
    colorTextSecondary: "#64748B",
    colorBackground: "#FFFFFF",
    colorInputBackground: "#FFFFFF",
    colorInputText: "#0F172A",
    colorDanger: "#EF4444",
    fontFamily: "var(--font-fredoka), system-ui, sans-serif",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "shadow-none w-full bg-transparent border-none px-0 py-0 gap-4",
    header: "hidden",
    footer: "hidden",
    footerAction: "hidden",
    socialButtons: "gap-3",
    socialButtonsBlockButton: {
      height: "44px",
      fontSize: "0.875rem",
      border: "1px solid #E5E7EB !important",
      boxShadow: "none !important",
      "&:hover": { boxShadow: "none" },
      "&:focus": { boxShadow: "none" },
      "&:active": { boxShadow: "none" },
    },
    socialButtonsBlockButtonText: "text-text-primary text-sm font-normal",
    dividerRow: "my-2",
    dividerLine: "bg-border",
    dividerText: "text-text-muted text-xs",
    formFieldRow: "mb-4",
    formFieldLabel: "text-text-secondary text-xs mb-1.5",
    formFieldInput: {
      height: "44px",
      border: "1px solid #E5E7EB !important",
      boxShadow: "none !important",
      fontSize: "0.875rem",
      "&:focus": { borderColor: "#3A90C3", boxShadow: "none" },
    },
    formButtonPrimary: {
      backgroundImage: "linear-gradient(90deg, #3A90C3 0%, #44BE4A 100%)",
      backgroundColor: "transparent",
      height: "44px",
      fontSize: "0.875rem",
      textTransform: "none",
      boxShadow: "none !important",
      border: "none",
      marginTop: "0.5rem",
      "&:hover": { opacity: 0.9, boxShadow: "none" },
      "&:focus": { boxShadow: "none" },
      "&:active": { boxShadow: "none" },
    },
    formResendCodeLink: "text-brand-blue",
    identityPreviewText: "text-text-primary text-sm",
    identityPreviewEditButton: "text-brand-blue",
    otpCodeFieldInput: { border: "1px solid #E5E7EB", boxShadow: "none !important" },
  },
};
