import { create } from "zustand";
import type { Product } from "@/types";

const seedProducts: Product[] = [
  // Infinite AUS
  { id: 1, name: "4 Channel Dimmer Device", sku: "DIMMER", brand: "Infinite AUS", category: "Light Controller", hsn: "85176990", description: "ON - OFF, DIMMABLE, ACCESS FROM ANYWHERE, VOICE COMMAND", price: null, status: "Active" },
  { id: 2, name: "2 Channel 10 AMP Device", sku: "10AMP", brand: "Infinite AUS", category: "Light Controller", hsn: "85176990", description: "ON - OFF, ACCESS FROM ANYWHERE, VOICE COMMAND", price: null, status: "Active" },
  { id: 3, name: "2 Channel Garage Door Device", sku: "GD-2C", brand: "Infinite AUS", category: "Garage Door Controller", hsn: "85176990", description: "Dry-Contact (2CH): Retrofit solution for automating motorized doors and gates operating at (240VAC)", price: null, status: "Active" },
  { id: 4, name: "HVAC AC Device", sku: "HVAC", brand: "Infinite AUS", category: "AC Controller", hsn: "85176990", description: "12-24V AC/DC solution offers seamless remote multi-zone control via Wi-Fi. Effortlessly manage temperatures", price: null, status: "Active" },
  { id: 5, name: "4 Channel Garage Door Device", sku: "ELV DRY", brand: "Infinite AUS", category: "Garage Door Controller", hsn: "85176990", description: "Dry-Contact (4CH): Retrofit solution for automating motorized doors and gates operating at (12-24VAC/DC)", price: null, status: "Active" },
  { id: 6, name: "Low Voltage 4 Channel Device", sku: "ELV_PWM", brand: "Infinite AUS", category: "Garage Door Controller", hsn: "85176990", description: "RGB CONTROLL, ON-OFF, DIMMABLE, ACCESS FROM ANYWHERE, VOICE COMMAND", price: null, status: "Active" },
  { id: 7, name: "ELV_WET", sku: "ELV_WET", brand: "Infinite AUS", category: "Garage Door Controller", hsn: "85176990", description: "", price: null, status: "Active" },
  { id: 8, name: "Dendo Curtain/Blind Motor", sku: "DECUMO", brand: "Infinite AUS", category: "Curtain Controller", hsn: "85176990", description: "Up - Down Functionality, Motorized Blinds, UP/Down/Stop Limit Settings", price: null, status: "Active" },
  { id: 9, name: "IR Device", sku: "IRD", brand: "Infinite AUS", category: "Infrared Controller", hsn: "85176990", description: "", price: null, status: "Active" },
  { id: 10, name: "Curtain/Blind Device", sku: "BCDEV", brand: "Infinite AUS", category: "Curtain Controller", hsn: "85176990", description: "Smart curtain/blind controller with wireless connectivity. Provides complete automation for motorized window treatments with programmable stop positions, soft-start features to prevent mechanical stress, and integration with smart home systems for scheduled operation.", price: null, status: "Active" },
  { id: 11, name: "Curtain/Blind Transmitter", sku: "BC TRANSMITTER", brand: "Infinite AUS", category: "Curtain Controller", hsn: "85176990", description: "Wireless remote transmitter for curtain and blind control. Portable controller featuring ergonomic design with intuitive buttons for up, down, and stop commands. Long-range wireless transmission with reliable signal strength for seamless operation.", price: null, status: "Active" },
  // Automation Products
  { id: 12, name: "Device Power Supply Cable", sku: "", brand: "Automation Products", category: "Light Controller", hsn: "85444999", description: "Industrial-grade power supply cable designed for automation devices. High-quality copper conductors with protective sheathing. Multiple gauge options available to support various power requirements for reliable device operation.", price: null, status: "Active" },
  { id: 13, name: "Light Power Supply Cable", sku: "", brand: "Automation Products", category: "Light Controller", hsn: "85444999", description: "Specialized power cable for lighting applications with optimal voltage regulation. Heavy-duty construction with safety certifications. Supports both AC and DC lighting systems with minimal power loss.", price: null, status: "Active" },
  { id: 14, name: "Switches Cable 4", sku: "", brand: "Automation Products", category: "Light Controller", hsn: "85444999", description: "4-conductor switch cable for light controller integration. Premium insulation provides excellent electrical safety and longevity. Suitable for multi-channel switching applications with consistent signal transmission.", price: null, status: "Active" },
  { id: 15, name: "Switches Cable 8 For Dry Contact", sku: "", brand: "Automation Products", category: "Garage Door Controller", hsn: "85444999", description: "8-conductor dry contact switching cable designed for garage door and gate control applications. Shielded design prevents electromagnetic interference. Meets industrial automation standards for reliable dry-contact operations.", price: null, status: "Active" },
  { id: 16, name: "SSR Relay", sku: "", brand: "Automation Products", category: "Light Controller", hsn: "85364900", description: "Solid State Relay (SSR) for electronic switching without moving contacts. Zero-crossing detection for AC switching applications. Supports up to 40A continuous current with built-in heat dissipation. Eliminates mechanical wear for extended operational life.", price: null, status: "Active" },
  { id: 17, name: "Reed Switch", sku: "", brand: "Automation Products", category: "Garage Door Controller", hsn: "85044090", description: "Magnetically-activated reed switch for door and window sensors. NO/NC configuration available for security applications. Low-power consumption with reliable switching at minimal contact resistance. Ideal for garage door position detection.", price: null, status: "Active" },
  // Electrical Product
  { id: 18, name: "Smart Locks", sku: "LOCKS", brand: "Electrical Product", category: "Locks", hsn: "83013000", description: "Advanced electronic lock system with multiple access methods including keypad, mobile app, and physical key. Temporary access codes for guests and service providers. Real-time access logs and alerts. Battery backup ensures operation during power loss.", price: null, status: "Active" },
  { id: 19, name: "Dimmable Light", sku: "LIGHT", brand: "Electrical Product", category: "Light", hsn: "94054090", description: "LED dimmable light fixture with smooth dimming capability from 0-100%. Color temperature tuning available (2700K-6500K). Energy-efficient design with 50,000+ hour lifespan. Compatible with wireless control systems and voice assistants.", price: null, status: "Active" },
  { id: 20, name: "Dimmable Light Driver", sku: "DRIVER", brand: "Electrical Product", category: "Driver", hsn: "94054090", description: "Electronic driver for dimmable LED lights offering flicker-free dimming control. Wide voltage input range 100-240V AC. PWM and 0-10V dimming modes supported. Built-in thermal protection and surge suppression for extended device longevity.", price: null, status: "Active" },
  { id: 21, name: "Cob / Panel Light", sku: "LIGHT", brand: "Electrical Product", category: "Light", hsn: "94054090", description: "Compact integrated LED COB/Panel light modules with high luminosity output. Uniform light distribution without hot spots. Various wattage options (10W-50W) available. Low heat generation with excellent color rendering index (CRI 90+).", price: null, status: "Active" },
  { id: 22, name: "Tunable Light", sku: "LIGHT", brand: "Electrical Product", category: "Light", hsn: "94054090", description: "Tunable white LED light with adjustable color temperature from warm white to cool daylight. Remote control adjustment for ambiance customization. Supports circadian rhythm lighting for improved sleep quality and productivity.", price: null, status: "Active" },
  { id: 23, name: "Tunable Light Driver", sku: "DRIVER", brand: "Electrical Product", category: "Driver", hsn: "94054090", description: "Advanced driver for tunable white LED systems with independent warm and cool LED control. Smooth color temperature transitions from 2700K to 6500K. Wireless control compatibility with scheduling and automation capabilities.", price: null, status: "Active" },
  { id: 24, name: "12 - 24 Volt Driver", sku: "DRIVER", brand: "Electrical Product", category: "Driver", hsn: "85044090", description: "Low-voltage DC driver for LED strips and panels operating at 12V or 24V. High conversion efficiency (>90%) with minimal power loss. Multiple output configurations for flexible wiring. Over-current and over-temperature protection included.", price: null, status: "Active" },
  { id: 25, name: "Led Strip Driver", sku: "DRIVER", brand: "Electrical Product", category: "Driver", hsn: "94054090", description: "LED strip driver for controlling high-brightness LED strip lighting. Supports PWM dimming control with adjustable frequency. Compatible with RGB and RGBW strips for multi-color applications. Compact design for space-efficient installations.", price: null, status: "Active" },
  { id: 26, name: "Power Adapter ( 12 - 24 V)", sku: "DRIVER", brand: "Electrical Product", category: "Driver", hsn: "85044090", description: "Universal power adapter with switchable 12V and 24V output selection. Wide input voltage compatibility (100-240V AC). Multiple output power options (30W to 120W). Built-in surge protection and EMI filtering for device safety.", price: null, status: "Active" },
  { id: 27, name: "Wire Tape", sku: "TAPE", brand: "Electrical Product", category: "Misc", hsn: "82032000", description: "Adhesive-backed wire management tape for organizing cables and wires. UV-resistant and temperature-stable for both indoor and outdoor use. Reusable design with strong holding power. Prevents tripping hazards and improves installation aesthetics.", price: null, status: "Active" },
  { id: 28, name: "RJ45 Connector", sku: "CONNECTOR", brand: "Electrical Product", category: "Misc", hsn: "85044090", description: "Standard RJ45 Category 6 network connectors for Ethernet connections. Gold-plated contacts for superior conductivity and corrosion resistance. Supports data transmission speeds up to 10Gbps. Suitable for networking and PoE devices.", price: null, status: "Active" },
  { id: 29, name: "Capacitor", sku: "CAPACITOR", brand: "Electrical Product", category: "Capacitor", hsn: "85044090", description: "High-reliability electrolytic and ceramic capacitors for power supply filtering and noise suppression. Various capacitance values (1µF to 10,000µF) available. Temperature-stable performance over -40°C to +85°C range. Used in device power conditioning circuits.", price: null, status: "Active" },
  // Wifi
  { id: 30, name: "U7 Pro XGS", sku: "U7-Pro-XGS", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Flagship WiFi 7 access point with ultra-high performance and extended range. Supports multiple simultaneous connections with low latency. Enterprise-grade security features with centralized management. large-scale deployments and high-bandwidth applications.", price: null, status: "Active" },
  { id: 31, name: "U7 Pro XG", sku: "U7-Pro-XG", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "High-performance WiFi 6E access point designed for demanding wireless applications. Delivers exceptional throughput and coverage across extended areas. Built-in AI-driven features for network optimization and automatic band steering.", price: null, status: "Active" },
  { id: 32, name: "U7 Pro Max", sku: "U7-Pro-Max", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Premium WiFi 6E access point offering maximum coverage and performance. Tri-band technology for simultaneous high-speed connections. Advanced features like band steering and air marshal to reduce interference and optimize network efficiency.", price: null, status: "Active" },
  { id: 33, name: "U7 Pro", sku: "U7-Pro", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Professional-grade WiFi 6 access point with excellent coverage and throughput. Enterprise-class features including guest network isolation and intrusion detection. Supports PoE+ for simplified installation with single cable deployment.", price: null, status: "Active" },
  { id: 34, name: "U7 Long Range", sku: "U7-LR", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Extended-range WiFi 6 access point optimized for large outdoor and indoor areas. Powerful directional antenna for maximum distance coverage. Weather-resistant design suitable for outdoor mounting on buildings and poles.", price: null, status: "Active" },
  { id: 35, name: "U7 Lite", sku: "U7-Lite", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Compact and affordable WiFi 6 access point for small to medium deployments. Full WiFi 6 performance in a space-saving form factor. Easy setup with centralized management and monitoring capabilities.", price: null, status: "Active" },
  { id: 36, name: "U6 Enterprise", sku: "U6-Enterprise", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Enterprise-class WiFi 6 access point with robust security and advanced management tools. High-capacity design supporting hundreds of simultaneous connections. Built-in network management for large-scale deployments.", price: null, status: "Active" },
  { id: 37, name: "U6 Pro", sku: "U6-Pro", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Professional WiFi 6 access point with excellent performance and security features. Tri-band operation provides dedicated backhaul connection for reliable mesh networking. Advanced QoS (Quality of Service) for prioritizing critical applications.", price: null, status: "Active" },
  { id: 38, name: "U6+", sku: "U6+", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "Dual-band WiFi 6 access point offering balanced performance and affordability. Compact design suitable for various mounting options. Easy integration with existing UniFi ecosystem for seamless network expansion.", price: null, status: "Active" },
  { id: 39, name: "AC Pro", sku: "UAP-AC-PRO", brand: "Wifi", category: "Wifi", hsn: "85176290", description: "High-power WiFi 5 (802.11ac) access point with excellent range and performance. Three external antennas for optimized signal coverage. PoE support for simplified deployment without additional power cabling.", price: null, status: "Active" },
  // Video Door Phone
  { id: 40, name: "G6 Pro Entry", sku: "UVC-G6-Pro-Entry", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Advanced video door phone with 4K recording capability and intelligent person detection. Wide 180-degree viewing angle for complete entrance coverage. Two-way audio with noise cancellation and emergency alert functionality.", price: null, status: "Active" },
  { id: 41, name: "G6 Entry", sku: "UVC-G6-Entry", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Full HD video door phone system for secure entrance monitoring. High-quality video streaming with low-latency two-way audio communication. Weatherproof design rated for harsh outdoor conditions. Cloud and local recording options available.", price: null, status: "Active" },
  { id: 42, name: "G3 Reader Pro", sku: "UA-G3-Pro", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Professional access control reader with advanced biometric support (fingerprint, facial recognition). Multiple credential formats including RFID, NFC, and mobile credentials. Real-time alert system with integration to central security management.", price: null, status: "Active" },
  { id: 43, name: "G2 Reader Pro", sku: "UA-G2-Pro", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Mid-range access reader with multiple authentication methods for secure entry control. Card and PIN code support with tamper detection. Log storage for detailed access history and audit trails.", price: null, status: "Active" },
  { id: 44, name: "Reader Flex", sku: "UA-G3-Flex", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Flexible access control reader supporting multiple credential types (cards, codes, mobile). Adjustable mounting options for various doorway configurations. Visual and audible feedback for user confirmation of access attempts.", price: null, status: "Active" },
  { id: 45, name: "G3 Reader", sku: "UA-G3", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Standard access control reader with RFID and NFC capability. Single or multi-door configuration options available. User-friendly LED indicators for access status feedback.", price: null, status: "Active" },
  { id: 46, name: "G2 Reader", sku: "UA-G2", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Entry-level access control reader with basic credential authentication. Simple setup and configuration for straightforward installations. Compact design suitable for retrofit applications.", price: null, status: "Active" },
  { id: 47, name: "Retrofit Reader", sku: "UA-Retrofit-Reader", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Specialized access reader designed for retrofit installations on existing doors. No modifications required to existing door frames. Backward-compatible with legacy access control systems.", price: null, status: "Active" },
  { id: 48, name: "G3 Intercom", sku: "UA-G3-Intercom", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Advanced IP intercom system with video capability and HD audio quality. Supports multiple doorbell cameras for multi-entrance monitoring. Mobile app integration for remote communication from anywhere.", price: null, status: "Active" },
  { id: 49, name: "Intercom", sku: "UA-Intercom", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Standard intercom system enabling two-way voice communication. Simple installation with hardwired connectivity. Volume control and call dismissal options for ease of use.", price: null, status: "Active" },
  { id: 50, name: "Access Ultra", sku: "UA-Ultra", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Premium access control platform combining video, audio, and access management. Cloud-based platform with real-time notifications and alerts. Comprehensive reporting and analytics for security insights.", price: null, status: "Active" },
  { id: 51, name: "G3 Reader Fingerprint", sku: "UA-G3-Fingerprint", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Biometric access reader with fingerprint recognition technology. Fast authentication with advanced anti-spoofing measures. Supports multiple fingerprints per user and visitor enrollment.", price: null, status: "Active" },
  { id: 52, name: "Retrofit Reader Fingerprint", sku: "UA-Retrofit-Reader-Fingerprint", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Fingerprint biometric reader designed for retrofit into existing access control systems. No structural modifications required. Seamless integration with current security infrastructure.", price: null, status: "Active" },
  { id: 53, name: "Intercom Viewer", sku: "UA-Intercom-Viewer", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Video intercom display unit for central communication and monitoring. Large touchscreen interface for intuitive operation. Supports multiple video sources from various entry points.", price: null, status: "Active" },
  { id: 54, name: "Enterprise Access Hub", sku: "EAH-8", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Centralized access control hub managing multiple readers and entry points. Advanced analytics and reporting for security compliance. Supports redundancy for mission-critical applications.", price: null, status: "Active" },
  { id: 55, name: "Retrofit Hub", sku: "UA-Retrofit-Hub-2", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Compact access control hub designed for retrofit installations. Minimal wiring requirements with flexible connectivity options. Scalable architecture for adding more readers as needed.", price: null, status: "Active" },
  { id: 56, name: "Door Hub", sku: "UA-Hub-Door", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Dedicated hub for door-level access control and monitoring. Integrated power supply with battery backup capability. Real-time synchronization with central management system.", price: null, status: "Active" },
  { id: 57, name: "Door Hub Mini", sku: "UA-Hub-Door-Mini", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Compact mini hub for single or dual-door access control applications. Space-efficient design for mounting in tight spaces. Full functionality with simplified configuration interface.", price: null, status: "Active" },
  { id: 58, name: "Gate Hub", sku: "UA-Hub-Gate", brand: "Video Door Phone", category: "Video Door Phone", hsn: "85311090", description: "Specialized hub for gate and perimeter access control. Support for high-power door strikes and electromagnetic locks. Weather-resistant enclosure for outdoor deployment.", price: null, status: "Active" },
  // Camera
  { id: 59, name: "G6 Pro Turret", sku: "UVC-G6-Pro-Turret", brand: "Camera", category: "Camera", hsn: "85258900", description: "Professional turret camera with 4K resolution and advanced AI analytics. Motorized zoom lens for detailed monitoring of distant areas. Intelligent person/vehicle detection with directional alerts.", price: null, status: "Active" },
  { id: 60, name: "G6 Pro Dome", sku: "UVC-G6-Pro-Dome", brand: "Camera", category: "Camera", hsn: "85258900", description: "Premium dome camera with 4K resolution and 360-degree coverage options. Discreet design for unobtrusive surveillance in professional environments. Smart tracking and automated alerting on detected threats.", price: null, status: "Active" },
  { id: 61, name: "G6 Turret", sku: "UVC-G6-Turret", brand: "Camera", category: "Camera", hsn: "85258900", description: "High-performance turret camera offering 4K video quality with excellent low-light performance. Wide zoom range for flexible monitoring scenarios. Reliable performance across extreme temperature ranges.", price: null, status: "Active" },
  { id: 62, name: "G6 Dome", sku: "UVC-G6-Dome", brand: "Camera", category: "Camera", hsn: "85258900", description: "Dome camera with 4K resolution and IK10 impact resistance. Vandal-proof construction suitable for high-risk areas. Built-in infrared LEDs for night vision capability.", price: null, status: "Active" },
  { id: 63, name: "G6 Pro 360", sku: "UVC-G6-Pro-360", brand: "Camera", category: "Camera", hsn: "85258900", description: "360-degree panoramic camera capturing complete area coverage without blind spots. 4K resolution for detailed monitoring in all directions. Dewarping technology for normal viewing of specific zones.", price: null, status: "Active" },
  { id: 64, name: "G6 180", sku: "UVC-G6-180", brand: "Camera", category: "Camera", hsn: "85258900", description: "Ultra-wide angle camera providing 180-degree horizontal coverage. Ideal for monitoring hallways, storefronts, and expansive areas. Single camera replaces multiple standard cameras for cost efficiency.", price: null, status: "Active" },
  { id: 65, name: "AI Multi Sensor 4", sku: "UVC-AI-MS-4", brand: "Camera", category: "Camera", hsn: "85258900", description: "AI-powered multi-sensor camera with 4 directional lenses for comprehensive coverage. Intelligent detection algorithms for person, vehicle, and object recognition. Advanced analytics with behavioral pattern detection.", price: null, status: "Active" },
  { id: 66, name: "G5 Turret Ultra", sku: "UVC-G5-Turret-Ultra", brand: "Camera", category: "Camera", hsn: "85258900", description: "High-performance turret camera with enhanced low-light imaging and 4K resolution. Powerful 30x optical zoom for detailed observation. Advanced thermal sensing options for 24/7 monitoring.", price: null, status: "Active" },
  { id: 67, name: "G6 Mini Dome", sku: "UVC-G6-Mini-Dome", brand: "Camera", category: "Camera", hsn: "85258900", description: "Compact mini dome camera with Full HD resolution. Space-efficient design for areas with limited installation space. Reliable performance with excellent color reproduction.", price: null, status: "Active" },
  { id: 68, name: "AI Turret", sku: "UVC-AI-Turret", brand: "Camera", category: "Camera", hsn: "85258900", description: "AI-enabled turret camera with intelligent video analytics capabilities. Real-time object tracking and behavioral analysis. Customizable alerts based on specific activity patterns and regions of interest.", price: null, status: "Active" },
  { id: 69, name: "AI Dome", sku: "UVC-AI-Dome", brand: "Camera", category: "Camera", hsn: "85258900", description: "AI-powered dome camera with advanced threat detection and classification. Automatic zoom to identified threats for detailed documentation. Supports cross-camera person tracking across multiple zones.", price: null, status: "Active" },
  { id: 70, name: "AI 360", sku: "UVC-AI-360", brand: "Camera", category: "Camera", hsn: "85258900", description: "360-degree AI camera with panoramic monitoring and intelligent analytics. Multiple simultaneous detections with tracking across the entire field of view. Supports various deployment scenarios without additional cameras.", price: null, status: "Active" },
  { id: 71, name: "G5 Dome", sku: "UVC-G5-Dome", brand: "Camera", category: "Camera", hsn: "85258900", description: "Reliable dome camera with Full HD resolution and IP67 weatherproofing. Vandal-resistant design for challenging environments. Efficient infrared illumination for night vision operations.", price: null, status: "Active" },
  { id: 72, name: "G5 Dome Ultra", sku: "UVC-G5-Dome-Ultra", brand: "Camera", category: "Camera", hsn: "85258900", description: "Enhanced G5 dome camera with improved low-light sensitivity and resolution. Supports extended monitoring range in dark environments. Durable construction for harsh weather conditions.", price: null, status: "Active" },
  { id: 73, name: "G6 Edge Turret", sku: "UVC-G6-Edge-Turret", brand: "Camera", category: "Camera", hsn: "85258900", description: "Edge-processing turret camera with on-device AI analytics. Reduced bandwidth usage through intelligent local processing. Compact design with professional mounting options.", price: null, status: "Active" },
  { id: 74, name: "G6 Edge Dome", sku: "UVC-G6-Edge-Dome", brand: "Camera", category: "Camera", hsn: "85258900", description: "Dome camera with edge computing for local video analytics processing. Lower storage and bandwidth requirements while maintaining analysis capabilities. Suitable for installations with limited network resources.", price: null, status: "Active" },
  { id: 75, name: "AI Multi Sensor 2", sku: "UVC-AI-MS-2", brand: "Camera", category: "Camera", hsn: "85258900", description: "Dual-sensor AI camera providing simultaneous wide-angle and zoom monitoring. Intelligent detection with simultaneous tracking of multiple subjects. Efficient bandwidth usage with smart compression.", price: null, status: "Active" },
  { id: 76, name: "G6 Pro Bullet", sku: "UVC-G6-Pro-Bullet", brand: "Camera", category: "Camera", hsn: "85258900", description: "Premium bullet camera with 4K resolution and motorized zoom lens. Sleek design suitable for visible deterrence installations. Advanced features including motion tracking and automated alerting.", price: null, status: "Active" },
  { id: 77, name: "G6 Bullet", sku: "UVC-G6-Bullet", brand: "Camera", category: "Camera", hsn: "85258900", description: "Professional bullet camera with 4K resolution and excellent weather resistance. Long-range monitoring capability with powerful zoom functionality. Ideal for perimeter security and outdoor surveillance.", price: null, status: "Active" },
  { id: 78, name: "G5 PRO", sku: "UVC-G5-Pro", brand: "Camera", category: "Camera", hsn: "85258900", description: "High-performance camera with advanced optical zoom and low-light enhancement. Professional-grade video quality with consistent performance in varying lighting conditions. Compact mounting options for flexible deployment.", price: null, status: "Active" },
  { id: 79, name: "G5 Bullet", sku: "UVC-G5-Bullet", brand: "Camera", category: "Camera", hsn: "85258900", description: "Durable bullet camera offering Full HD resolution and reliable performance. Extended operational range with excellent color accuracy. Suitable for long-term outdoor surveillance applications.", price: null, status: "Active" },
  { id: 80, name: "G6 Edge Bullet", sku: "UVC-G6-Edge-Bullet", brand: "Camera", category: "Camera", hsn: "85258900", description: "Edge-computing bullet camera with integrated analytics processing. Efficient network usage through edge AI capabilities. Professional appearance with discreet mounting.", price: null, status: "Active" },
  { id: 81, name: "G6 Instant", sku: "UVC-G6-INS", brand: "Camera", category: "Camera", hsn: "85258900", description: "Instant deployment camera ideal for temporary or rapid-response monitoring. Quick setup without complex configuration requirements. Portable design for flexible repositioning as needed.", price: null, status: "Active" },
  { id: 82, name: "Camera AI Theta Pro", sku: "UVC-AI-Theta-Pro", brand: "Camera", category: "Camera", hsn: "85258900", description: "360-degree panoramic AI camera with comprehensive threat detection. Dewarping capabilities for normal viewing of specific zones. Advanced AI analytics for intelligent security monitoring.", price: null, status: "Active" },
  { id: 83, name: "G5 Flex", sku: "UVC-G5-Flex", brand: "Camera", category: "Camera", hsn: "85258900", description: "Flexible mounting camera with Full HD resolution and wide viewing angles. Adaptable to various mounting configurations and angles. Reliable performance for diverse surveillance scenarios.", price: null, status: "Active" },
  // Sensors & Alarms
  { id: 84, name: "Glass Break Sensor", sku: "USL-GlassBreak", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "85311090", description: "Advanced glass break detection sensor using acoustic analysis. Distinguishes genuine glass breakage from loud noises (traffic, thunder). Wireless connectivity with instant alert transmission to security system.", price: null, status: "Active" },
  { id: 85, name: "Environmental Sensor", sku: "USL-Environmental", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "90258090", description: "Multi-parameter environmental monitoring sensor measuring temperature, humidity, and air pressure. Real-time data logging and alerts for abnormal conditions. Applications in HVAC monitoring, storage facilities, and climate-sensitive areas.", price: null, status: "Active" },
  { id: 86, name: "Vape Detection & Air Quality Sensor", sku: "UP-AirQuality", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "90271000", description: "Advanced sensor detecting vaping activity and monitoring air quality metrics. Measures PM2.5, PM10, CO2, and volatile organic compounds (VOCs). Instant alerts for policy violations in restricted areas.", price: null, status: "Active" },
  { id: 87, name: "Relay", sku: "USL-Relay", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "83564900", description: "Electronic relay module for switching high-current loads with low-level control signals. Multiple relay options for different switching requirements. Isolation between control and switching circuits for safety.", price: null, status: "Active" },
  { id: 88, name: "Remote Control KeyFob", sku: "USL-FOB", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "85269200", description: "Wireless remote control fob for arming/disarming and control operations. Long-range transmission with encrypted signal for security. Compact design with intuitive button layout and status indicators.", price: null, status: "Active" },
  { id: 89, name: "Alarm Hub Kit", sku: "UP-AlaramHub-Kit", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "85311090", description: "Complete alarm system hub with wireless sensor connectivity and central management. Battery backup for continued operation during power outages. Mobile app notifications and remote arming/disarming capabilities.", price: null, status: "Active" },
  { id: 90, name: "Siren PoE", sku: "UP-Siren-PoE", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "85311090", description: "Power-over-Ethernet siren providing high-decibel alarm output with PoE power supply. Eliminates need for separate power wiring during installation. IP-rated weatherproof design for indoor and outdoor use.", price: null, status: "Active" },
  { id: 91, name: "Siren", sku: "USL-Siren", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "85311090", description: "High-output siren for alarm system alert and evacuation signaling. 120dB+ decibel level for attention-getting alerts. Weather-resistant construction for reliable operation in various environments.", price: null, status: "Active" },
  { id: 92, name: "AI Speaker", sku: "UP-AI-Speaker", brand: "Sensors & Alarms", category: "Sensors & Alarms", hsn: "85182100", description: "Smart speaker with AI voice assistant integration and advanced audio processing. Two-way audio communication with noise suppression technology. Integration with security system for voice-controlled alerts and notifications.", price: null, status: "Active" },
  // Advance Hosting
  { id: 93, name: "Gateway Fiber", sku: "UXG-Fiber(30W)", brand: "Advance Hosting", category: "Advance Hosting", hsn: "85176290", description: "High-performance gateway supporting fiber connectivity with 30W PoE budget. Enterprise-class security and routing capabilities. Supports large-scale deployments with multiple wireless access points.", price: null, status: "Active" },
  { id: 94, name: "Gateway Light", sku: "UXG-Lite", brand: "Advance Hosting", category: "Advance Hosting", hsn: "85176290", description: "Lightweight entry-level gateway for small business and residential networks. Simplified setup with automatic configuration features. Sufficient PoE budget for standard access point and camera deployments.", price: null, status: "Active" },
  { id: 95, name: "Gateway Max", sku: "UXG-Max", brand: "Advance Hosting", category: "Advance Hosting", hsn: "85176290", description: "Maximum-capacity gateway with highest performance and PoE budget allocation. Supports extensive network expansion with numerous access points. Advanced security features with DPI (Deep Packet Inspection).", price: null, status: "Active" },
  { id: 96, name: "Gateway Pro", sku: "UXG-Pro", brand: "Advance Hosting", category: "Advance Hosting", hsn: "85176290", description: "Professional-grade gateway balancing performance and scalability for mid-range deployments. Adequate PoE budget for mixed device deployments. Enhanced security with intrusion prevention and threat detection.", price: null, status: "Active" },
  { id: 97, name: "Cloud Key Enterprise", sku: "CK-Enterprise", brand: "Advance Hosting", category: "Advance Hosting", hsn: "85176290", description: "Enterprise-class controller with cloud backup and redundancy capabilities. Supports unlimited user accounts and devices. Advanced security audit trails and compliance reporting.", price: null, status: "Active" },
  { id: 98, name: "Cloud Key+", sku: "UCK-G2-SSD", brand: "Advance Hosting", category: "Advance Hosting", hsn: "85176290", description: "Enhanced cloud controller with increased storage (SSD) for longer local recording retention. Reliable backup power and failover capabilities. Centralized management for multiple sites.", price: null, status: "Active" },
  // Managed VoIP
  { id: 99, name: "G3 Touch Enterprise", sku: "UTP-G3-Touch-Enterprise", brand: "Managed VoIP", category: "Managed VoIP", hsn: "85171800", description: "Enterprise VoIP touchscreen phone with large HD display for communication and device control. Advanced call management with conferencing and transfer capabilities. Integration with business applications and directories.", price: null, status: "Active" },
  { id: 100, name: "G3 Touch Pro", sku: "UTP-G3-Touch-Pro", brand: "Managed VoIP", category: "Managed VoIP", hsn: "85171800", description: "Professional touchscreen VoIP phone with feature-rich communication tools. Intuitive interface with customizable shortcuts for frequently used functions. Excellent audio quality with full-duplex speakerphone.", price: null, status: "Active" },
  { id: 101, name: "G3 Touch Wall", sku: "UTP-G3-Touch-Wall", brand: "Managed VoIP", category: "Managed VoIP", hsn: "85171800", description: "Wall-mounted VoIP touchscreen for communal areas and reception desks. Space-efficient design with readable display from distance. Multi-user capability for shared workspace communication.", price: null, status: "Active" },
  { id: 102, name: "G2 Touch Max", sku: "UTP-TouchMax", brand: "Managed VoIP", category: "Managed VoIP", hsn: "85171800", description: "Premium touchscreen VoIP phone with maximum features and display size. Supports video calling with camera integration. Advanced security features for business communication.", price: null, status: "Active" },
  { id: 103, name: "G2 Touch", sku: "UTP-Touch", brand: "Managed VoIP", category: "Managed VoIP", hsn: "85171800", description: "Standard touchscreen VoIP phone combining communication and control features. User-friendly interface for easy operation. Reliable performance for everyday business communication needs.", price: null, status: "Active" },
  { id: 104, name: "G3 Wireless Handset", sku: "UT-G3-Handset", brand: "Managed VoIP", category: "Managed VoIP", hsn: "85171800", description: "Wireless handset compatible with VoIP phone systems and desk phones. Encrypted communication for secure business conversations. Extended range with excellent audio quality and interference resistance.", price: null, status: "Active" },
  { id: 105, name: "Analog Telephone Adapter", sku: "UT-ATA", brand: "Managed VoIP", category: "Managed VoIP", hsn: "85171800", description: "Converts analog phone lines to VoIP for seamless integration with existing systems. Supports both single and dual-port configurations. Emergency 911 support and failover options available.", price: null, status: "Active" },
];

function normalizeCategory(raw: string): string {
  let v = raw.trim();
  v = v.replace(/Garrage/g, "Garage");
  v = v.replace(/Contoller/g, "Controller");
  v = v.replace(/Conroller/g, "Controller");
  v = v.replace(/Alarams/g, "Alarms");
  return v;
}

interface ProductStore {
  products: Product[];
  nextId: number;
  add: (p: Omit<Product, "id">) => void;
  update: (id: number, patch: Partial<Omit<Product, "id">>) => void;
  remove: (id: number) => void;
  bulkAdd: (items: Omit<Product, "id">[]) => void;
  setAll: (items: Product[]) => void;
  brands: () => string[];
  categories: () => string[];
  categoriesByBrand: (brand: string) => string[];
  brandsByCategory: (category: string) => string[];
  productsByBrandCategory: (brand: string, category: string) => Product[];
}

export const useProductStore = create<ProductStore>((set, get) => ({
  products: seedProducts,
  nextId: 106,
  add: (p) =>
    set((s) => ({ products: [...s.products, { ...p, id: s.nextId }], nextId: s.nextId + 1 })),
  update: (id, patch) =>
    set((s) => ({
      products: s.products.map((p) => (p.id === id ? { ...p, ...patch } : p)),
    })),
  remove: (id) =>
    set((s) => ({ products: s.products.filter((p) => p.id !== id) })),
  bulkAdd: (items) =>
    set((s) => {
      let id = s.nextId;
      const newProducts = items.map((p) => ({ ...p, id: id++, category: normalizeCategory(p.category) }));
      return { products: [...s.products, ...newProducts], nextId: id };
    }),
  setAll: (items) => set({ products: items }),
  brands: () => [...new Set(get().products.map((p) => p.brand))].sort(),
  categories: () => [...new Set(get().products.map((p) => p.category))].sort(),
  categoriesByBrand: (brand) =>
    [...new Set(get().products.filter((p) => p.brand === brand).map((p) => p.category))].sort(),
  brandsByCategory: (category) =>
    [...new Set(get().products.filter((p) => p.category === category).map((p) => p.brand))].sort(),
  productsByBrandCategory: (brand, category) =>
    get().products.filter((p) => p.brand === brand && p.category === category && p.status === "Active"),
}));

